Presentation/missions_youtube_links.UI.Web/Models/users_view_model.cs
using missions_youtube_links.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace missions_youtube_links.UI.Web.Models
{
    public class users_view_model
    {
        public IEnumerable<user_dto> lst_dto { get; set; }
        public user_dto dto { get; set; }
    }
}

Presentation/missions_youtube_links.UI.Web/Controllers/MissionsController.cs
using missions_youtube_links.Business;
using missions_youtube_links.Data;
using missions_youtube_links.Entities;
using missions_youtube_links.UI.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace missions_youtube_links.UI.Web.Controllers
{
    public class MissionsController : Controller
    {
        public string TAG;
        //Event declaration:
        //event for publishing messages to output
        public event EventHandler<notificationmessageEventArgs> _notificationmessageEventname;
        //list to hold messages
        public List<notificationdto> _lstnotificationdto = new List<notificationdto>();

        public MissionsController()
        {

            TAG = this.GetType().Name;

            AppDomain.CurrentDomain.UnhandledException += new
UnhandledExceptionEventHandler(UnhandledException);
            System.Windows.Forms.Application.ThreadException += new ThreadExceptionEventHandler(ThreadException);

            //Subscribing to the event: 
            //Dynamically:
            //EventName += HandlerName;
            _notificationmessageEventname += notificationmessageHandler;

            _notificationmessageEventname.Invoke(this, new notificationmessageEventArgs("finished MissionsController initialization", TAG));

        }
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {

        }
        private void UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            Exception ex = (Exception)e.ExceptionObject;
            helper_utils.getInstance(_notificationmessageEventname).log_messages(ex.ToString(), TAG);
            //Log.Write_To_Log_File_temp_dir(ex);
            _notificationmessageEventname.Invoke(this, new notificationmessageEventArgs(ex.ToString(), TAG));
        }

        private void ThreadException(object sender, ThreadExceptionEventArgs e)
        {
            Exception ex = e.Exception;
            //Log.Write_To_Log_File_temp_dir(ex);
            helper_utils.getInstance(_notificationmessageEventname).log_messages(ex.ToString(), TAG);
            _notificationmessageEventname.Invoke(this, new notificationmessageEventArgs(ex.ToString(), TAG));
        }

        //Event handler declaration:
        private void notificationmessageHandler(object sender, notificationmessageEventArgs args)
        {
            try
            {
                /* Handler logic */
                notificationdto _notificationdto = new notificationdto();

                DateTime currentDate = DateTime.Now;
                String dateTimenow = currentDate.ToString("dd-MM-yyyy HH:mm:ss tt");

                String _logtext = Environment.NewLine + "[ " + dateTimenow + " ]   " + args.message;

                _notificationdto._notification_message = _logtext;
                _notificationdto._created_datetime = dateTimenow;
                _notificationdto.TAG = args.TAG;

                Console.WriteLine(args.message);

                _lstnotificationdto = (from msg in _lstnotificationdto
                                       orderby msg._created_datetime descending
                                       select msg).ToList();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        // GET: Missions
        [HttpGet]
        public ActionResult Index([Bind] missions_links_dto search_model)
        {
            try
            {
                missions_links_dto dto = new missions_links_dto();
                missions_view_model model = new missions_view_model();
                List<missions_links_dto> _lst_dtos = new List<missions_links_dto>();

                _lst_dtos = populate_dtos(_lst_dtos);

                if (_lst_dtos != null)
                {
                    Console.WriteLine("Missions count: " + _lst_dtos.Count());
                    TempData["success_message"] = "Retrieved [ " + _lst_dtos.Count() + " ] records.";
                    _notificationmessageEventname.Invoke(this, new notificationmessageEventArgs("Retrieved [ " + _lst_dtos.Count() + " ] records.", TAG));
                    helper_utils.getInstance(_notificationmessageEventname).log_messages("Retrieved [ " + _lst_dtos.Count() + " ] records.", TAG);
                }
                else
                {
                    model.dto = populate_model(dto);
                    TempData["error_message"] = "Error retrieving data.";
                    _notificationmessageEventname.Invoke(this, new notificationmessageEventArgs("Error retrieving data.", TAG));
                    helper_utils.getInstance(_notificationmessageEventname).log_messages("Error retrieving data.", TAG);
                    return View();
                }

                model.lst_dto = _lst_dtos;
                model.dto = populate_model(dto);

                //Display the records
                return View(model);
            }
            catch (Exception ex)
            {
                TempData["error_message"] = ex.ToString();
                helper_utils.getInstance(_notificationmessageEventname).log_messages(ex.ToString(), TAG);
                error_handler_view_model error_model = new error_handler_view_model();
                error_model.ex = ex;
                return View("Error_View", error_model);
            }
        }
        private List<missions_links_dto> populate_dtos(List<missions_links_dto> _lst_dtos)
        {
            DataTable dt = null;
            string query = "";
            bool showinactive = true;
            string server = "sqlite"; //selected_server.Key;

            if (showinactive)
            {
                query = DBContract.missions_links_entity_table.SELECT_ALL_QUERY;
            }
            else
            {
                query = DBContract.missions_links_entity_table.SELECT_ALL_FILTER_QUERY;
            }

            dt = businesslayerapisingleton.getInstance(_notificationmessageEventname).get_missions(showinactive, query, DBContract.sqlite);

            if (dt != null)
            {
                _lst_dtos = utilzsingleton.getInstance(_notificationmessageEventname).Convert_DataTable_To_list<missions_links_dto>(dt);
                _lst_dtos = _lst_dtos.OrderByDescending(i => i.id).ThenBy(t => t.description).ToList();

                Console.WriteLine("Missions count: " + _lst_dtos.Count());
            }
            else
            {
                return null;
            }

            foreach (missions_links_dto mission in _lst_dtos)
            {
                var year = int.Parse(mission.mission_year);
                var month = int.Parse(mission.mission_month);
                var day = int.Parse(mission.mission_day);

                DateTime date = new DateTime(year, month, day);
                string day_name = date.ToString("dddd");
                string month_name = date.ToString("MMMMM");

                mission.mission_day_str = day_name;
                mission.mission_month_str = month_name;
            }
            return _lst_dtos;
        }

        private missions_links_dto populate_model(missions_links_dto model)
        {
            List<SelectListItem> mission_types = new List<SelectListItem>();
            List<SelectListItem> years = new List<SelectListItem>();
            List<SelectListItem> months = new List<SelectListItem>();
            List<SelectListItem> days = new List<SelectListItem>();

            Dictionary<string, string> mission_types_dic = new Dictionary<string, string>()
            { 
                {"Healing Service","Healing Service"},
                {"Pastors Conference","Pastors Conference"},
                {"Word Expo","Word Expo"},
                {"Miracle","Miracle"},
                {"Prophecy","Prophecy"},
                {"Prophecy Fullfilment","Prophecy Fullfilment"},
                {"Blessings","Blessings"},
                {"Grand Reception","Grand Reception"},
                {"Repentance Service","Repentance Service"},
            };

            SelectListItem mstp = new SelectListItem()
            {
                Value = null,
                Text = "--- Select Type ---"
            };

            //SelectList mission_types_lst = new SelectList(mission_types_dic.Select(x => new { Value = x.Key, Text = x.Value }), "Value", "Text");

            foreach (KeyValuePair<string, string> mission_type in mission_types_dic)
            {
                SelectListItem sli = new SelectListItem()
                {
                    Value = mission_type.Key,
                    Text = mission_type.Value
                };
                mission_types.Add(sli);
            }

            mission_types.Insert(0, mstp);

            model.mission_types = mission_types;

            List<string> _years = new List<string>();

            DateTime startyear = DateTime.Now;
            while (startyear.Year >= DateTime.Now.AddYears(-80).Year)
            {
                _years.Add(startyear.Year.ToString());
                startyear = startyear.AddYears(-1);
            }

            SelectListItem sli_yr = new SelectListItem()
            {
                Value = null,
                Text = "--- Select Year ---"
            };

            years.Add(sli_yr);

            foreach (string yr in _years)
            {
                SelectListItem sli = new SelectListItem()
                {
                    Value = yr,
                    Text = yr
                };
                years.Add(sli);
            }

            model.mission_years = years;

            months.Add(new SelectListItem { Value = null, Text = "--- Select Month ---" });
            months.Add(new SelectListItem { Value = "1", Text = "January" });
            months.Add(new SelectListItem { Value = "2", Text = "February" });

Presentation/missions_youtube_links.UI.Web/Views/Users/add_user.cshtml
@model missions_youtube_links.Entities.user_dto

@{
    ViewBag.Title = "Create User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="page-title">Create User</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frm_add_user" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Ensure all required fields are filled.</legend>

        <div class="add_user">

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "form-label" })
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @required = "required", @class = "form-control", @placeholder = "Email", @type = "email" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "lbl_error text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "form-label" })
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @required = "required", @class = "form-control", @placeholder = "Password", @type = "password" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "lbl_error text-danger" })
                <p id="" class="">Password must be 8 and above characters and must contain an upper case letter, lower case letter, a number and a symbol.</p>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fullnames, htmlAttributes: new { @class = "form-label" })
                @Html.EditorFor(model => model.fullnames, new { htmlAttributes = new { @required = "required", @class = "form-control", @placeholder = "Full Names", @type = "text" } })
                @Html.ValidationMessageFor(model => model.fullnames, "", new { @class = "lbl_error text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "form-label" })
                @Html.DropDownListFor(model => model.gender, new SelectList(Model.genders, "Value", "Text"), new { @class = "form-control", @id = "cbogender" })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "lbl_error text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.year, htmlAttributes: new { @class = "form-label" })
                @Html.DropDownListFor(model => model.year, new SelectList(Model.years, "Value", "Text"), new { @class = "form-control", @id = "cboyears" })
                @Html.ValidationMessageFor(model => model.year, "", new { @class = "lbl_error text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.month, htmlAttributes: new { @class = "form-label" })
                @Html.DropDownListFor(model => model.month, new SelectList(Model.months, "Value", "Text"), new { @class = "form-control", @id = "cbomonths" })
                @Html.ValidationMessageFor(model => model.month, "", new { @class = "lbl_error text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.day, htmlAttributes: new { @class = "form-label" })
                @Html.DropDownListFor(model => model.day, new SelectList(Model.days, "Value", "Text"), new { @class = "form-control", @id = "cbodays" })
                @Html.ValidationMessageFor(model => model.day, "", new { @class = "lbl_error text-danger" })
            </div>

        </div>

        <div class="form-group div_btn">
            <input type="submit" value="Create" class="btn btn-success btn_class" />
            @Html.ActionLink("Users", "Index", "Users", null, new { @class = "btn btn-primary btn_class" })
        </div>

    </fieldset>
}
 
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {

            $("#email").focus();
             
            document.getElementById('cbomonths').addEventListener('change', function (event) {
                event.preventDefault();
                load_month_days();
            });

            function load_month_days() {
                var selectedyear = $("#cboyears").val();
                var selectedmonth = $("#cbomonths").val();
                var cbodays = $("#cbodays");
                cbodays.empty();

                if (selectedyear != null && selectedyear != '' && selectedmonth != null && selectedmonth != '') {
                    $.getJSON('@Url.Action("getmonthdays")',
                        {
                            year: selectedyear,
                            month: selectedmonth
                        }, function (days) {
                            console.log(days);
                            if (days != null && !jQuery.isEmptyObject(days)) {
                                $.each(days, function (index, day) {
                                    console.log(day);
                                    console.log(index);
                                    cbodays.append($('<option/>', {
                                        value: day.Value,
                                        text: day.Text
                                    }))
                                })
                            }
                        });
                }
            }

            $("#cbomonths").on("change", function () {


            });




        });

    </script>
}

Presentation/missions_youtube_links.UI.Web/Views/Users/delete_user.cshtml
@{
    ViewBag.Title = "delete_user";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>delete_user</h2>

Presentation/missions_youtube_links.UI.Web/Views/Users/details.cshtml
@{
    ViewBag.Title = "details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>details</h2>

Presentation/missions_youtube_links.UI.Web/Views/Users/edit_user.cshtml
@{
    ViewBag.Title = "edit_user";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>edit_user</h2>

Presentation/missions_youtube_links.UI.Web/Views/Users/login.cshtml
@model missions_youtube_links.Entities.user_dto

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frm_login" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>

        <div class="login">

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "form-label" })
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @required = "required", @class = "form-control", @placeholder = "Email", @id = "txtemail", @autofocus = "autofocus", @autocomplete = "autocomplete", @type = "email" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "lbl_error text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "form-label" })
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @required = "required", @class = "form-control", @placeholder = "Password", @id = "txtpassword", @type = "password" } })
                <span id="lblshowpassword">Show Password</span>
                <input type="checkbox" id="chkshowpassword" class="checkbox" name="chkshowpassword" />
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "lbl_error text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Login" id="btnlogin" class="btn btn-success btn_class" />
            </div>

        </div>

    </fieldset>
}


<!-- Modal for progress-->
<div class="modal fade" id="progressModal" tabindex="-1"
     role="dialog" data-backdrop="static"
     aria-labelledby="progressModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="progressModalLabel">
                    processing...
                </h5>
            </div>
            <div class="modal-body">

                <div id="progress_container" class="progress">
                    <div id="progressbar"
                         class="progress-bar indeterminate progress-bar-warning progress-bar-striped progress-bar-animated active"
                         role="progressbar"
                         aria-valuenow="0"
                         aria-valuemin="0"
                         aria-valuemax="100"
                         style="width: 100%">
                        <span id="current-progress"></span>
                    </div>

                </div>


                <div id="div_progress_msg" class="text-center"></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary"
                        data-dismiss="modal">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Modal ends here -->




@section Scripts {

    <script type="text/javascript">

        $(document).ready(function () {

            //document.getElementById('btnlogin').addEventListener('click', function (event) {
            //    event.preventDefault();
            //    //login();
            //});

            document.getElementById('chkshowpassword').addEventListener('click', function (event) {
                event.preventDefault();
                show_hide_password();
            });

            document.getElementById('lblshowpassword').addEventListener('click', function (event) {
                event.preventDefault();
                show_hide_password();
            });

            function show_hide_password() {
                const txtpassword = document.getElementById("txtpassword");
                const chkshowpassword = document.getElementById("chkshowpassword");

                if (chkshowpassword.checked) {
                    txtpassword.type = "text";
                }
                else {
                    txtpassword.type = "password";
                }

            }

            //login
            function login() {

                showprogressmodal();
                showprogressbar();

                // get form fields values
                var email = $("#txtemail").val();
                var password = $("#txtpassword").val();

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Login", "Users")',
                    data: {
                        "email": email,
                        "password": password
                    } //data to be posted
                }).done(function (data) {

                    // hide modal popup
                    hideprogressmodal();

                    hideprogressbar();

                    // redirect to admin page
                    //window.location = @*@Url.Action("Index", "Missions")';*@

                }).fail(function (jqXHR, textStatus) {

                    hideprogressbar();
                });

                //hideprogressbar();

            }

            function hideprogressbar() {
                // $(".progress").css("display", "none");
                // $(".progress-bar").css("display", "none");
                $('.progress').fadeOut(2000); // hide the element using timer
                $('.progress-bar').fadeOut(2000); // hide the element using timer
                hide_toast();
            }

            function showprogressbar() {
                // $(".progress").css("display", "block");
                // $(".progress-bar").css("display", "block");
                $('.progress').fadeIn(100); // display the element using timer
                $('.progress-bar').fadeIn(100); // display the element using timer
                show_toast();
            }

            function showprogressmodal() {
                // Open modal popup
                $("#progressModal").modal("show");
            }

            function hideprogressmodal() {
                // hide modal popup
                $("#progressModal").modal("hide");
            }

        });

    </script>
}